version: '3'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3005
    environment: 
      PORT: 3005
      REACT_APP_INTERNEO_API: http://localhost:8080
    
  database:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app

  nginx:
    image: nginx:1.17
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dbdata:
    driver: local
