#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
secure:
    path:       /
    controller: App\Controller\MainController::secure
    schemes:    [https]